Development.
pashabetenya/Mova pull request #2
Opened 2023-04-07 00:31 UTC by pashabetenya

2023-04-10 23:32 UTC, pashabetenya commented
I do the division into widgets, 
and use a made-up part of the structure. 

Eventually the application will be moved to a clean architecture, 


and comments are for me :)

2023-04-12 09:37 UTC, Vovanella95 requested changes
Please, fix comments.

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/authorization/authorization_page.dart
> +    final height = MediaQuery.of(context).size.height;
please do not use mediaQuery. Try to use Expanded widget instead

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/authorization/authorization_page.dart
> +  Widget content(height) {
please do not use methods, returning widget. Use private widgets instead. Methods broke application performance

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/authorization/authorization_page.dart
> +          LogotypeWidget(color: const Color(0xFFF1F1F5), height: height * 0.06),
Try to not use height. Use Align, Expanded, Flexible widgets instead

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/authorization/authorization_page.dart
> +  Widget panel(height) {
Do not use methods, returning widgets (Check everywhere)

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/authorization/authorization_page.dart
> +          SizedBox(height: height * 0.02),
Do not use height. (Check everywhere)

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/authorization/components/authorization_description.dart
> +        fontFamily: 'MontserratRegular',
Too many parameters of TextStyle. Maybe better to create TextStyle presets and use them across the app?

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/authorization/components/authorization_material_button.dart
> +  void transition(context) {
bad method name.
Also, method should be private. 
Place private methods below the public methods

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/authorization/components/authorization_material_button.dart
> +      width: MediaQuery.of(context).size.width,
Again strange calculations. Rid of it

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/authorization/components/authorization_text_button.dart
> +  TextStyle get textStyle1 => TextStyle(
textStyle1? What does it means?

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/authorization/components/authorization_text_button.dart
> +  TextStyle get textStyle2 => TextStyle(
Same comment as for textStyle1

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/login/components/login_text_button.dart
> +  void transition(context) {
Bad method name

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/login/components/login_text_button.dart
> +    final width = MediaQuery.of(context).size.width;
Rid of width and calculations

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/login/login_page.dart
> +                SizedBox(height: height * 0.085),
Remove dependence from height

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/onboarding/components/onboarding_indicator.dart
> +  const OnboardingIndicator({Key? key, required this.indicator}) : super(key: key);
required properties should be placed before optional

2023-04-12 09:37 UTC, Vovanella95 commented on lib/ui/pages/onboarding/components/onboarding_material_button.dart
> +  void transition(context) {
Bad method name

2023-04-17 17:51 UTC, merged